language: python
sudo: false

python:
- '3.6'

install:
  - travis_retry pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest
  - pytest --cov=sparse_kmedoids/
after_success:
  - coveralls